customhost = "newemployee.chm22smkaknh.us-east-2.rds.amazonaws.com"
customuser = "dbcreator"
custompass = "intellipath"
customdb = "newemployee"
custombucket = "addemploy1"
customregion = "us-east-2"
